version: '2'
services:

# Create Database Server
  mysql:
    image: mysql:5.5.52
    container_name: mysql
    restart: always
    volumes:
      - ./mysql/mysql.conf.d/:/etc/mysql/mysql.conf.d
      - ./mysql/data/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ROOTpassword
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wp
      - MYSQL_PASSWORD=WPpassword

#Create Web Server -> NGINX
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/log:/var/log/nginx
      - ./certs:/etc/ssl:ro
    volumes_from:
      - php-fpm
    ports:
      - 80:80
      - 443:443

  php-fpm:
    build: ./php-fpm
    container_name: php-fpm
    restart: always
    volumes:
      - ./www:/var/www/html/
    expose:
      - "9000"

  php-apache:
    build: ./php
    container_name: php-apache
    restart: always
    ports:
      - 8080:80
#      - 443:443
    volumes:
      - ./www:/var/www/html/
      - ./apache/sites-available:/etc/apache2/sites-available
      - ./apache/logs:/var/log/apache2
      - ./certs:/etc/ssl

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
#      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    restart: always
    ports:
      - 8000:80
