version: '2'

services:
  mysql:
    image: mysql:5.5.52
    container_name: mysql
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ROOTpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    volumes:
      - ./wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wordpress
    depends_on:
      - mysql
    ports:
      - 80:80